### ISSUE TITLE
Nexus 9: Auto-Focus Messed Up for RFC

### ISSUE THREAD

**Issue by commonsguy** [commonsguy/cwac-cam2#106]
Run demo app. Tap FAB to take picture. Watch as the auto-focus rapid-fire goes in and out. Add hack for this, to disable auto-focus, at least on 5.1.1 (retest on 6.0 once upgrade rolls around, as the M Developer Preview does not exhibit this behavior).

**Comment by markini** [comment]
I think I have the same issue on 6.0. When taking the photo the auto-focus makes the preview very blurry (depending on light and distance --> it is definitively worse than every other device I have at my disposal).

N9, 6.0, MRA58K

**Comment by commonsguy** [comment]
Addressed in v0.3.2.

**Comment by markini** [comment]
Oh, my device has 
`Build.MANUFACTURER` = `HTC`
`Build.PRODUCT` = `VOLANTISG`

**Comment by commonsguy** [comment]
@markini Just to confirm -- those are both in all caps?

**Comment by markini** [comment]
Oh sorry, don't know how this ended up in all caps (had an app which printed it all caps). It's all in lowercase letters. 
Here a dalvik explorer screenshot:

![nexus_9_3g](https://cloud.githubusercontent.com/assets/1747400/10792683/01905846-7d8e-11e5-93d4-ccb0a1769498.png)

**Comment by commonsguy** [comment]
Addressed in v0.3.4.
