### ISSUE TITLE
Support Flash Modes

### ISSUE THREAD

**Issue by commonsguy** [commonsguy/cwac-cam2#11]
Users should be able to toggle through flash modes via the floating action menu, for the flash modes that are available on the device.

There should be an `IntentBuilder` method and corresponding extra for providing the desired starting flash mode. Possibly, make this an array extra with preferences in descending order.

**Comment by commonsguy** [comment]
Addressed in v0.4.0.

**Comment by jaumecolom** [comment]
@commonsguy How can we switch the Flash mode, through a button?

**Comment by commonsguy** [comment]
I added support to allow you to control the flash mode as a developer, but the FAM is not in place yet. That got moved to issue #126. My apologies -- I should have been clearer in this issue.
