### ISSUE TITLE
Move FocusMode Out Of AbstractCameraActivity

### ISSUE THREAD

**Issue by commonsguy** [commonsguy/cwac-cam2#114]
For the eventual `cam2-support` work (issue #20), we need to get as much stuff out of the activities and fragments as possible. One item is `FocusMode`, presently in `AbstractCameraActivity`. Move this someplace else (not quite certain where...) that can be central to both implementations.

**Comment by zokipirlo** [comment]
I would suggest `CameraSelectionCriteria`. Also for `Facing`.

**Comment by commonsguy** [comment]
@zokipirlo `FocusMode` has nothing to do with selecting a camera, so `CameraSelectionCriteria` would not make sense. More likely, it will become just a top-level enum. `Facing` could go on `CameraSelectionCriteria`, since that actually is involved in selecting a camera.

**Comment by commonsguy** [comment]
Addressed in v0.5.0.
