### ISSUE TITLE
Screen Orientation

### ISSUE THREAD

**Issue by nzisis** [commonsguy/cwac-cam2#125]
Hey guys I just used your library and it is awesome. I got some questions . When I take a picture  with portrait screen orientation the result is a rotate picture. And when I take a picture with landscape screen orientation the result is okay. Can I check the orientation of the camera and then display properly the picture? 

Looking forward for your reply
Regards Nick

**Comment by commonsguy** [comment]
> I got some questions 

Please read [the documentation](https://github.com/commonsguy/cwac-cam2#questions) for instructions of where to ask questions.

> When I take a picture with portrait screen orientation the result is a rotate picture

See https://stackoverflow.com/a/30596702/115145 and issue #15 for more about this.
