### ISSUE TITLE
Switch to Better Orientation Calculation in ClassicCameraEngine

### ISSUE THREAD

**Issue by commonsguy** [commonsguy/cwac-cam2#127]
While fixing issue #121, I noticed that my display orientation work differs from [what `setDisplayOrientation()` recommends](http://developer.android.com/reference/android/hardware/Camera.html#setDisplayOrientation%28int%29). Right now, the right algorithm (at least for previews) is used for the Nexus 6P and nothing else, since everything else seems to work.

For v0.5.0, try switching to the new algorithm for everything.

**Comment by NicodeLee** [comment]
Sound good！

**Comment by commonsguy** [comment]
Addressed in v0.5.0.
