### ISSUE TITLE
Wrong orientation on android 6 (Marshmallow) 

### ISSUE THREAD

**Issue by Zuhair-Kj** [commonsguy/cwac-cam2#135]
I am not sure whether this is because of the device (Nexus 5X) or the new OS version
but the camera orientation is reverted see image in link:
https://drive.google.com/file/d/0ByP6surFrliGTUtGaldPcExYQ0E/view?usp=sharing

I cannot lock the orientation because I need the correct orientation of the image.

**Comment by commonsguy** [comment]
Please provide complete steps to reproduce the problem.

**Comment by Zuhair-Kj** [comment]
@commonsguy 
```java
intent = new CameraActivity.IntentBuilder(QuickSellActivity.this).skipConfirm()
                            .to(tempOutputFileUri)
                            .forceClassic()
                            .build();
startActivityForResult(intent, IMAGE_CAPTURE_CODE);
```

**Comment by commonsguy** [comment]
Before filing other issues, please read the contribution guidelines for [instructions on submitting bug reports](https://github.com/commonsguy/cwac-cam2/blob/master/CONTRIBUTING.md#contributing-bug-reports).

I can reproduce your problem using the `demo-playground` app, with "Save full image to file" checked, "Force classic API" checked, and everything else at their defaults, from a fresh install of that app.

**Comment by commonsguy** [comment]
Duplicate of issue #130

**Comment by commonsguy** [comment]
Try v0.4.4, as I have added the Nexus 5X to the alternative orientation algorithm whitelist, and that seems to clear up the problem.
