### ISSUE TITLE
Inconsistent image result orientation issues with the CameraView

### ISSUE THREAD

**Issue by 4netinteractive** [commonsguy/cwac-cam2#137]
We are experiencing some orientation issues with the image that is returned from the `CameraEngine.PictureTakenEvent`.

One some devices the image made when holding the phone portrait are returned portrait and on some devices the image is returned landscape.

To illustrate this problem I have attached a sample project that can be found [here CWACCam2Orientation](https://github.com/4netinteractive/CWACCam2Orientation)

An example of the orientation issues are displayed here below. The images are displayed in phone holding direction.

# Screenshots
My opinion is that only the image response of 'Samsung Galaxy S6 5.1.1 Portrait' is incorrect.
## Example
* The small `red` block is the image returned from the `CameraEngine.PictureTakenEvent`
* The large `green` block is the preview (`CameraView`)

![Explanation](https://raw.githubusercontent.com/4netinteractive/CWACCam2Orientation/master/Screenshots/Explanation.png)

#### Motorola G (3rd) 5.1.1 Landscape and Image Landscape
![Motorola G (3rd) 5.1.1 Landscape](https://github.com/4netinteractive/CWACCam2Orientation/blob/master/Screenshots/Motorola%20G%20(3rd)%205.1.1%20Landscape.png?raw=true)

#### Motorola G (3rd) 5.1.1 Portrait and Image Portrait
![Motorola G (3rd) 5.1.1 Portrait](https://github.com/4netinteractive/CWACCam2Orientation/blob/master/Screenshots/Motorola%20G%20(3rd)%205.1.1%20Portrait.png?raw=true)

#### Samsung Galaxy S6 5.1.1 Landscape and Image Landscape
![Samsung Galaxy S6 5.1.1 Landscape](https://github.com/4netinteractive/CWACCam2Orientation/blob/master/Screenshots/Samsung%20Galaxy%20S6%205.1.1%20Landscape.png?raw=true)

#### Samsung Galaxy S6 5.1.1 Portrait and Image Landscape
![Samsung Galaxy S6 5.1.1 Portrait]
(https://github.com/4netinteractive/CWACCam2Orientation/blob/master/Screenshots/Samsung%20Galaxy%20S6%205.1.1%20Portrait.png?raw=true)

**Comment by commonsguy** [comment]
> We are experiencing some orientation issues with the image that is returned from the CameraEngine.PictureTakenEvent.

Note that this is part of the internal implementation and is not part of the supported API of this library.

Otherwise, this would appear to be normal output from device cameras. See issue #15.

If you have some evidence that would indicate that this is not merely a question of EXIF headers, please comment back here, and I can reopen the issue.
