### ISSUE TITLE
Add Better Resolution Control Options

### ISSUE THREAD

**Issue by commonsguy** [commonsguy/cwac-cam2#142]
At minimum, have a low-vs.-high option. Consider some sort of min-resolution/max-resolution settings, with failure if the camera is incapable of meeting those specifications.

**Comment by commonsguy** [comment]
Addressed in v0.5.6 by making `quality()` work for both still photos and videos.

**Comment by eygraber** [comment]
Any chance of adding some kind of middle option? With my pixel I'm stuck between getting a 144x176 or 3036x4048.

**Comment by commonsguy** [comment]
@eygraber I would recommend that you look at more flexible libraries, such as [Fotoapparat](https://github.com/Fotoapparat/Fotoapparat) or possibly [CameraKit-Android](https://github.com/gogopop/CameraKit-Android).
