### ISSUE TITLE
Auto Focus is not working with samsung S Dous

### ISSUE THREAD

**Issue by mobiloitte-varun-jain** [commonsguy/cwac-cam2#145]
Please let me know why the auto focus is not working with samsung S Dous...
It is working fine with other devices but Auto focus and auto flash is not working with samsung s Dous.

**Comment by commonsguy** [comment]
Please follow [the instructions for submitting a bug report](https://github.com/commonsguy/cwac-cam2/blob/master/CONTRIBUTING.md#contributing-bug-reports).

**Comment by commonsguy** [comment]
Closing as not reproducible, given lack of specifics.
