### ISSUE TITLE
Dependecies

### ISSUE THREAD

**Issue by nickfl** [commonsguy/cwac-cam2#153]
By some reason cannot add line
       **compile 'com.commonsware.cwac:cam2:0.5.+'**
to my dependencies - error "Failed to resolve.."

**Comment by commonsguy** [comment]
This is an issue tracker, not a support board. Please [read the documentation](https://github.com/commonsguy/cwac-cam2#questions) to find out where and how to get support.

Make sure that you added the `repositories` closure as described in [the documentation](https://github.com/commonsguy/cwac-cam2#installation). You can see full working `build.gradle` files for [the `demo` app](https://github.com/commonsguy/cwac-cam2/blob/master/demo/build.gradle) and for [the `demo-playground` app](https://github.com/commonsguy/cwac-cam2/blob/master/demo-playground/build.gradle).
