### ISSUE TITLE
Handle orientation change

### ISSUE THREAD

**Issue by PFittech** [commonsguy/cwac-cam2#163]
How I can listen to orienation change? I want rotate icon in camera preview depend on orientation.

**Comment by commonsguy** [comment]
Modifying the camera preview is outside [the scope of the API of this project](https://github.com/commonsguy/cwac-cam2#basic-usage).

Also, this is an issue tracker, not a support board. [The documentation](https://github.com/commonsguy/cwac-cam2#questions) explains how to get support.
