### ISSUE TITLE
Record Video

### ISSUE THREAD

**Issue by ihsanbal** [commonsguy/cwac-cam2#169]
How can i record video square like instagram using cwac-cam or cwac-cam2?
Recording screen
=======
![screenshot_20160323-091536](https://cloud.githubusercontent.com/assets/3420514/13978226/3806ce4c-f0d8-11e5-8641-4af4707b9cda.png)

Recorded Video
=======
![screenshot_20160323-091619](https://cloud.githubusercontent.com/assets/3420514/13978279/73f84610-f0d8-11e5-8939-a1cb2510d938.png)

**Comment by commonsguy** [comment]
I do not know what "cwac-cam" is. The CWAC-Camera project is discontinued. Square video recording is not supported by CWAC-Cam2.
