### ISSUE TITLE
Application crashes if there is some error saving image

### ISSUE THREAD

**Issue by lujop** [commonsguy/cwac-cam2#170]
If there are some error saving image( JPEGWriter) an *UnsupportedOperationException* is throw and there's no way to manage that and prevent Application crash.

I think that an error has to be reported in activityResult or a least log it and continue silently. Anything instead of an application crash.

**Comment by commonsguy** [comment]
> If there are some error saving image( JPEGWriter) an UnsupportedOperationException is throw and there's no way to manage that and prevent Application crash.

It is your job to take appropriate steps to ensure that the supplied path will work and that there is sufficient storage space for a photo, *before* trying to take a photo. This should eliminate most cases where writing the JPEG would fail.

That being said, I have opened issue #171 as an enhancement request for offering a better path for this sort of thing.

I am going to close this issue in favor of issue #171. If you have specific comments regarding `JPEGWriter`, comment on this issue, as I can reopen it if needed.
