### ISSUE TITLE
CameraDevice was already closed

### ISSUE THREAD

**Issue by sljjyy** [commonsguy/cwac-cam2#174]
【Xperia P】
java.lang.IllegalStateException: CameraDevice was already closed
resultCode = 0

**Comment by commonsguy** [comment]
Please read [the contribution guidelines](http://stackoverflow.com/questions/8327514/comparison-method-violates-its-general-contract) and follow the instructions for submitting a bug report.

**Comment by commonsguy** [comment]
Closing for lack of sufficient information.
