### ISSUE TITLE
Support Zoom

### ISSUE THREAD

**Issue by commonsguy** [commonsguy/cwac-cam2#18]
The Google Camera app supports zoom in/out via pinch gestures. Offer some sort of zoom option (gestures? something else?). Make sure this supports optical and digital zoom on relevant devices. Make sure that this fails gracefully on zoom-less devices.

**Comment by saurabhjain1592** [comment]
Did this thing was implemented. Now this API supports zoom in and out of camera, if then can you tell me how to include it in my application?

**Comment by commonsguy** [comment]
> Did this thing was implemented. 

Not yet. That is why this issue is open.

**Comment by commonsguy** [comment]
Note to self: see pull request #140 for a sample implementation.

**Comment by commonsguy** [comment]
Addressed in v0.5.0.
