### ISSUE TITLE
Allow aspect ratio selecting in IntentBuilder

### ISSUE THREAD

**Issue by lujop** [commonsguy/cwac-cam2#199]
Allow to configure a desired aspect ratio in IntentBuilder  that is honored if it's possible.

For example if you want to take a square photo of a contact and phone camera already has a preview size that is adapted to that size it's better than make the user crop it after photo is done.

**Comment by commonsguy** [comment]
That's unrealistic. I have a rough enough time with aspect ratios as it stands. Bear in mind that preview size != available preview visible area != picture size. A square preview means nothing in terms of a picture.

From what I have seen, few devices support a square aspect ratio for preview frames or pictures. This means that the user experience would be highly variable (this device, they get a square; this other device, they do not).

Moreover, fussing with custom aspect ratios is well outside the scope of this library. This library is meant to be a replacement for `ACTION_IMAGE_CAPTURE`, and ideally be fairly small in terms of lines of code that I have to maintain.
