### ISSUE TITLE
Captured images are different than preview from camera - Motorola moto g(2nd gen)

### ISSUE THREAD

**Issue by bossik21** [commonsguy/cwac-cam2#205]
Hi,

I have a strange problem on my phone (Motorola moto g - 2nd gen). I have made photos using your demo application and added it below.

**Portrait - Rear**
1. Result photo is rotated by 90 degree.
2. I set the camera position so that the edges of the preview were blue edges on the picture.  But there is an additional space next to"RIGHT" border on created photo.

**Landscape - Rear**
1.  I set the camera position so that the edges of the preview were blue edges on the picture. But there is an additional space under the "BOTTOM" border on created photo. 

[cam2_motorola_thea_reteu_20160518-152303.zip](https://github.com/commonsguy/cwac-cam2/files/270644/cam2_motorola_thea_reteu_20160518-152303.zip)

Problems are just on rear camera. 

Thanks

**Comment by commonsguy** [comment]
With regards to orientation, see issue #15. With regards to preview size, see issue #204.
