### ISSUE TITLE
[Question] Is image/video guaranteed already saved when return from Intent? 

### ISSUE THREAD

**Issue by terao318** [commonsguy/cwac-cam2#206]
I tried to make application which process large image/video captured from cwac-cam2.
on onActivityResult, do I need to add delay to make sure data is completely written to disk, before I can process/read the image/video file?

**Comment by commonsguy** [comment]
Please, *this is an issue tracker*. Either [follow the contribution guidelines](https://github.com/commonsguy/cwac-cam2/blob/master/.github/CONTRIBUTING.md) for filing bug reports and such, or follow [the support instructions for asking questions](https://github.com/commonsguy/cwac-cam2#questions). 

For still photos, the files should be fully written to disk before control returns to you in `onActivityResult()`. For videos, `MediaRecorder` is responsible for the file, not my code, and so I cannot offer any guarantees regarding the state of that file at the point of `onActivityResult()`.
