### ISSUE TITLE
[Question] How to change "picture button" color?

### ISSUE THREAD

**Issue by bkawakami** [commonsguy/cwac-cam2#207]
I would like to modify the color of picture button, but I don't know which element in the style should receive the color.

Change the green button(is the default color), to blue, for example.

Can anybody help me?

**Comment by bkawakami** [comment]
Well... I just put over this color:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="cwac_cam2_picture_fab">#81aad9</color>
</resources>
```

**Comment by commonsguy** [comment]
Yes, that would be the resource to override. Sorry for the delay in responding.
