### ISSUE TITLE
Video preview is upside down when using front camera vertically

### ISSUE THREAD

**Issue by shalevmo** [commonsguy/cwac-cam2#222]
When I take a video using the front camera and the phone orientation is vertical, the video output is upside down.

**Comment by commonsguy** [comment]
Please follow [the contribution guidelines](https://github.com/commonsguy/cwac-cam2/blob/master/.github/CONTRIBUTING.md) and provide:

- the `Build.MANUFACTURER` and `Build.PRODUCT` values for the hardware on which you are experiencing the problem
- the code necessary to reproduce the problem (this could be one of the demo apps, or it could be some demo project of yours that you publish)
- the steps necessary, using that code and that hardware, to reproduce the problem

**Comment by shalevmo** [comment]
I have a Nexus 6P , running Android 6.0.1 (MTC19V).
All I did was to take a video using the sample code:

`  Intent i=new VideoRecorderActivity.IntentBuilder(MainActivity.this)
      .quality(Quality.LOW)
      .facing(VideoRecorderActivity.Facing.FRONT)
      .to(new File(testRoot, "test.mp4"))
      .debug()
      .updateMediaStore()
      .build();`

then, when I watch the video in any video player, it is upside down.

**Comment by commonsguy** [comment]
There are two portrait orientations. Have you tried both?

**Comment by shalevmo** [comment]
only the normal portrait orientation is working for me.
when i try to flip my phone it goes to one of the landscape orientations

**Comment by commonsguy** [comment]
I can reproduce the problem on a 6P and will look into it in my next development pulse on this. Thanks!

**Comment by shalevmo** [comment]
thank you very much!,  i'll be waiting.
BTW, are there any planes to add flashlight toggle?

**Comment by commonsguy** [comment]
I have no idea what a "flashlight toggle" is. If you mean user-selectable flash modes, see issue #126.

**Comment by commonsguy** [comment]
Addressed in v0.6.2.
