### ISSUE TITLE
CWAC cam2 memory issue

### ISSUE THREAD

**Issue by laltukumar-1473** [commonsguy/cwac-cam2#224]
I am using 4.4 version of cwac cam2 library and calling the Intent class to capture the image.
Once the image is captured. Its taking lot of memory in my app. Is there any way to reduce the memory usage.

**Comment by commonsguy** [comment]
This is an issue tracker, not a support board. Please [follow the instructions](https://github.com/commonsguy/cwac-cam2#questions) for getting support.

> I am using 4.4 version of cwac cam2 library

There is no 4.4 version. I assume that you mean 0.4.4.

> Is there any way to reduce the memory usage.

Use the `android:process` attribute to isolate the `CameraActivity` in its own process:

```
<activity
      android:name="com.commonsware.cwac.cam2.CameraActivity"
      android:process=":cwac_cam2" />
```

(substituting in whatever you want for the process name, so long as it begins with a `:`)

This will keep the library's memory usage out your main process and ensure that it gets freed up when the work is completed.
