### ISSUE TITLE
Move FAB Based on Actual Orientation When Locked

### ISSUE THREAD

**Issue by commonsguy** [commonsguy/cwac-cam2#234]
If `orientationLockMode()` locks the orientation to `PORTRAIT` or `LANDSCAPE`, the FAB winds up being locked there too, which puts it in an odd spot as the user rotates the device. Ideally, the FAB will move even in orientation-locked mode. This should include any future `DEFAULT` lock-to-the-current-location-while-capturing logic.

**Comment by yeskunall** [comment]
This would be a great addition. Since this project is no longer being maintained, any tips/ideas on how to implement this? Thanks! ❤️

**Comment by commonsguy** [comment]
I never really looked into this much, sorry.
