### ISSUE TITLE
[hike] Change access modifier for methods used from UI level

### ISSUE THREAD

**Issue by atul-bsb** [commonsguy/cwac-cam2#236]
Please make the following methods public,
- AbstractCameraActivity.IntentBuilder.buildChooserBaseIntent
- CameraController.setCurrentCamera
- CameraController.changeZoom

I will re-open this if I come across anymore method (unlikely) which needs similar changes. Thanks!

**Comment by commonsguy** [comment]
Released in v0.6.4.
