### ISSUE TITLE
Samsung Galaxy S6 edge running on ClassicCameraEngine

### ISSUE THREAD

**Issue by ankur-j9** [commonsguy/cwac-cam2#242]
I have samsung galaxy s6 edge device, when i run this library on device, it is running with the ClassicCameraEngine's instance whereas device support Camera2. when debug the code, DeviceMatcher.supportsCameraTwo() is returning false for it.

**Comment by commonsguy** [comment]
This is intentional. The only devices that will use the `android.hardware.camera2` API are ones that I test and that I confirm work OK with that API (and my library's code for it).
