### ISSUE TITLE
The preview is zoomed when I start recording with front camera Sony Xperia M4

### ISSUE THREAD

**Issue by mikes01** [commonsguy/cwac-cam2#243]
Sony Xperia M4 Android 5.0 - when I use front-camera at demo-playground app the video preview is zoomed at the start of the recording. Nevermind If I use Classic camera or Camera 2 engine.

**Comment by commonsguy** [comment]
Once recording starts, I have no further control over the video preview.

I am going to guess that your problem is what I have has issue #173. You can follow that issue, or comment back here if you feel that your situation is different than that issue.
