### ISSUE TITLE
use still camera to capture multiple photos

### ISSUE THREAD

**Issue by ShivamHacks** [commonsguy/cwac-cam2#245]
I want to capture multiple photos at once (not a burst) but instead allow the user to take one photo, then take another, then another, etc. until they choose to exit the activity. Meanwhile, the in background, every time a photo is taken I want to save it/upload it to a server. Is this possible with the current API, and if so how can I implement this.

**Comment by commonsguy** [comment]
Sorry, but that is outside the scope of this project at this time.
