### ISSUE TITLE
Support Auto-Focus Modes

### ISSUE THREAD

**Issue by commonsguy** [commonsguy/cwac-cam2#25]
In addition to issue #14 (tap-to-focus), better support auto-focus modes. Since the Google Camera app does not appear to have these as end-user-configurable, settle for `IntentBuilder` method and corresponding extra. Normalize the possible modes based upon both APIs. Try to support continuous auto-focus.

**Comment by gbhall** [comment]
Continuous auto-focus would be amazing!

**Comment by tmiyamon** [comment]
I'm waiting for this feature!

**Comment by commonsguy** [comment]
Addressed in v0.3.0.

**Comment by gbhall** [comment]
@commonsguy I just want to say excellent work with the autofocus, I love it.

**Comment by commonsguy** [comment]
@gbhall Thanks!
