### ISSUE TITLE
the beginning of the video is darker

### ISSUE THREAD

**Issue by mikes01** [commonsguy/cwac-cam2#251]
Hello,
I'm using front camera from cwac-cam2 lib on HTC ONE M8 with Android 6.0.0. The first ~0,5s is darker than the rest of the movie. This is really annoying. Have you had similar issue? do you now how can i resolve it?

**Comment by commonsguy** [comment]
> Have you had similar issue?

I have not been measuring the relative darkness of different portions of recorded video. That being said, I have not noticed anything.

> do you now how can i resolve it?

Cut off the first ~0,5s of the video, I guess. I have no control over `MediaRecorder`, let alone the underlying hardware, so whatever gets recorded is what gets recorded.

Also, in the future, please follow [the instructions for getting support](https://github.com/commonsguy/cwac-cam2#questions).
