### ISSUE TITLE
Exception java.lang.IllegalStateException: Activity has been destroyed

### ISSUE THREAD

**Issue by mehdimasrour** [commonsguy/cwac-cam2#257]
Hello

Some users of my app have crashes when taking a picture.

Stack trace :

`Exception java.lang.IllegalStateException: Activity has been destroyed
android.app.FragmentManagerImpl.enqueueAction (FragmentManager.java:1455)
android.app.BackStackRecord.commitInternal (BackStackRecord.java:687)
android.app.BackStackRecord.commit (BackStackRecord.java:663)
com.commonsware.cwac.cam2.CameraActivity.removeFragments (CameraActivity.java:233)
com.commonsware.cwac.cam2.CameraActivity.access$000 (CameraActivity.java:31)
com.commonsware.cwac.cam2.CameraActivity$2.run (CameraActivity.java:175)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:158)
android.app.ActivityThread.main (ActivityThread.java:7231)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)`

The code is as simple as :

Intent i = new CameraActivity.IntentBuilder(HomeActivity.this)
.to(ImageUtils.getOutputMediaFileUri(ImageUtils.MEDIA_TYPE_IMAGE))
.skipConfirm()
.zoomStyle(ZoomStyle.SEEKBAR)
.updateMediaStore()
.build();
startActivityForResult(i, CAPTURE_IMAGE_ACTIVITY_REQUEST_CODE);

Device :
Manufacturer Samsung
Model SM-J510FN
OS 6.0.1
cwac-cam2 0.6.7

I can't reproduce it on my OnePlus 3 but every user of my app with some other phone has this crash (reports in Google Play Console)

Thank you in advance,

Regards

**Comment by commonsguy** [comment]
Addressed in v0.6.9.
