### ISSUE TITLE
Cameraview size

### ISSUE THREAD

**Issue by dbof10** [commonsguy/cwac-cam2#259]
I have a cameraview size of 200x200dp as a small preview. How to set aspect ratio 1:1 for the camera? How to capture photo as what is shown on the cameraview?

**Comment by commonsguy** [comment]
> I have a cameraview size of 200x200dp as a small preview

That is not supported. [The only supported API is through the `IntentBuilders`](https://github.com/commonsguy/cwac-cam2#basic-usage).

> How to set aspect ratio 1:1 for the camera?

That is not supported.

> How to capture photo as what is shown on the cameraview?

That is not supported.

I strongly encourage you to use the camera APIs directly.
