### ISSUE TITLE
it doesnt save video file in external storage in marsemallow phone.

### ISSUE THREAD

**Issue by saravanan72** [commonsguy/cwac-cam2#260]
it doesnt save video file in external storage in marsemallow phone. even permission is giving.. it shows error like showing below..
![screenshot_20160930-130809](https://cloud.githubusercontent.com/assets/7361575/18984480/76bd647e-8710-11e6-9683-610d460bd0fe.png)

**Comment by commonsguy** [comment]
This is an issue tracker. Please follow [the instructions for getting support](https://github.com/commonsguy/cwac-cam2#questions).

Perhaps you do not have a video player on that device.
