### ISSUE TITLE
repository  issues

### ISSUE THREAD

**Issue by SoNep** [commonsguy/cwac-cam2#277]
Error:A problem occurred configuring project ':app'.
> A problem occurred configuring project ':
   > Could not resolve all dependencies for configuration ':
      > Could not resolve com.commonsware.cwac:cam2:0.7.0.
        Required by:
            
         > Could not resolve com.commonsware.cwac:cam2:0.7.0.
            > Could not get resource 'https://repo.commonsware.com.s3.amazonaws.com/com/commonsware/cwac/cam2/0.7.0/cam2-0.7.0.pom'.
               > Could not HEAD 'https://repo.commonsware.com.s3.amazonaws.com/com/commonsware/cwac/cam2/0.7.0/cam2-0.7.0.pom'.
                  > Host name 'repo.commonsware.com.s3.amazonaws.com' does not match the certificate subject provided by the peer (CN=*.s3.amazonaws.com, O=Amazon.com Inc., L=Seattle, ST=Washington, C=US)

**Comment by commonsguy** [comment]
That is not the correct repo URL. Please use the one in [the current documentation](https://github.com/commonsguy/cwac-cam2#installation).
