### ISSUE TITLE
Encrypt image file with AES key

### ISSUE THREAD

**Issue by SoNep** [commonsguy/cwac-cam2#283]
I create pull request for encrypt image file with AES key

**Comment by commonsguy** [comment]
I appreciate the work that you put into this. However, there are two problems:

1. As I mention in [the contribution guidelines](https://github.com/commonsguy/cwac-cam2/blob/master/.github/CONTRIBUTING.md#contributing-code), I cannot accept substantial pull requests.

2. This library should not contain encryption logic, any more than it contains image-processing logic. I need to keep the scope of this library to something that I can manage. And, when it comes to encryption, there are *many* variables (encryption algorithm, key-stretching algorithm, salting, initialization vectors, etc.), more than I want to deal with in the library itself.

It *should* be possible to encrypt the images saved via this library. However, that should be done by either a `ContentProvider` (see issue #284) or, eventually, via a `ParcelFileDescriptor` (see issue #285). Basically, I should be able to pass the raw bytes over to your code in memory, where you can encrypt them yourself as part of writing them to disk, saving them in a `BLOB` column of the database, or anything else. This allows you to do your encryption without having to modify the library.

The `ContentProvider` approach should work now, where issue #284 is merely demonstrating and documenting it.

I apologize for not directly accepting your pull request, though my hope is that through issue #284 and issue #285, I can meet your needs through a different implementation.
