### ISSUE TITLE
how can i get camera preview on my own xml ?

### ISSUE THREAD

**Issue by santoshthorani** [commonsguy/cwac-cam2#292]
cwac cam2 does not have CameraHostProvider interface so how can i use camera preview and other actions on my own xml?

**Comment by commonsguy** [comment]
This is an issue tracker, not a support board. There are [multiple support options described in the documentation](https://github.com/commonsguy/cwac-cam2#questions). Please use those.

> how can i use camera preview and other actions on my own xml?

The library does not support this. In the end, you will need to use the camera APIs yourself directly. You are certainly welcome to copy code from this project into yours, subject to the license terms. However, I am not providing technical support for that.
