### ISSUE TITLE
selfie FFC - always shifted to right on preview?

### ISSUE THREAD

**Issue by shahzadyounas** [commonsguy/cwac-cam2#296]
This has been an ongoing issue since 0.6 - but I thought I would raise it now - the selfie FFC camera - when the preview shows myself directly in the centre, I then take a photo and every time it is very shifted to the right? (ie chopping half of my face).

Test device HTC 10 but have seen same issue in others.

Also - many reports from various devices that the selfie is quite dark? (camera preview is dark)

Not sure if you have come across this or have any advice?

Thx

**Comment by commonsguy** [comment]
Please [follow the instructions for filing bug reports](https://github.com/commonsguy/cwac-cam2/blob/master/.github/CONTRIBUTING.md#contributing-bug-reports).

**Comment by commonsguy** [comment]
Closing as not reproducible.
