### ISSUE TITLE
Add Timer Option

### ISSUE THREAD

**Issue by commonsguy** [commonsguy/cwac-cam2#297]
Configure this via an extra and associated `IntentBuilder` method, for still images (not video). If set, and if the user has not taken a picture within the supplied number of seconds, take the picture automatically, as if the user had pressed the FAB.

**Comment by jaumebalust** [comment]
this would be excellent

**Comment by commonsguy** [comment]
Also needs to add reverse `Chronometer` to this to show the countdown.

**Comment by commonsguy** [comment]
Added in v0.7.4.
