### ISSUE TITLE
Unable to customize the CameraActivity theme.

### ISSUE THREAD

**Issue by abhijeet-gupta** [commonsguy/cwac-cam2#298]
Hello,
I am using your library for capturing an image in my app. But I want to change the theme of CameraActivity according to my app such as change the Floating Action button color, zoom seek bar color.
I used your library via maven coordinate. I defined the custom theme for activity tag in my manifest file but it does not make any changes.

Please help me to customise the CameraActivity.

**Comment by commonsguy** [comment]
This is an issue tracker. This is not a support board. The documentation has [a section on how to get support](https://github.com/commonsguy/cwac-cam2#questions).

Adding documentation (and, where needed, code changes) for custom themes is already noted in issue #21.
