### ISSUE TITLE
Remove settings button

### ISSUE THREAD

**Issue by bkawakami** [commonsguy/cwac-cam2#306]
How can I remove settings button? Can I access the fragment to set visible to gone?

**Comment by commonsguy** [comment]
**This is an issue tracker, not a support board. Please follow [the instructions on the site for getting support](https://github.com/commonsguy/cwac-cam2#questions).**

> How can I remove settings button?

There is no option for this. The user needs to be able to choose the camera (e.g., their FFC is broken and so they need to use the rear-facing camera).

> Can I access the fragment to set visible to gone?

That is not supported.
