### ISSUE TITLE
Replace Exif code with standard google lib

### ISSUE THREAD

**Issue by xp-vit** [commonsguy/cwac-cam2#307]
Recently google released their own Exif support lib:
https://android-developers.googleblog.com/2016/12/introducing-the-exifinterface-support-library.html

Probably it worth switching to this one, instead of having exif code in repo. Hoever, quick look shows that some functionality is missing in this lib, e.g. : 
exif.removeCompressedThumbnail();

**Comment by commonsguy** [comment]
AFAIK, the Android Support Library edition of `ExifInterface` is missing stuff that I am using. So, while ideally I would use theirs, I do not think that is possible at the present time.
