### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by spapapan** [commonsguy/cwac-cam2#313]
Hey, I would like to try your library but when I add compile 'com.commonsware.cwac:cam2:0.7.4' in the dependancies I get the error:

Failed to resolve: com.commonsware.cwac:cam2:0.7.4

**Comment by commonsguy** [comment]
Make sure that you have the `repositories` closure described in [the documentation](https://github.com/commonsguy/cwac-cam2#installation).

**Comment by WaresTrader** [comment]
I really wish I knew how to help, great with pc but challenged with this ..

**Comment by commonsguy** [comment]
Closing as not reproducible.
