### ISSUE TITLE
Easy Integration in fragment

### ISSUE THREAD

**Issue by jatin-lakhani** [commonsguy/cwac-cam2#318]
Hey,

The library is awesome but its typical complex to integrate.

Can you provide easy step to integrate camera capture module into fragment ?

Thanks in advance

**Comment by commonsguy** [comment]
> The library is awesome but its typical complex to integrate.

Integrating the library is a matter of creating an `Intent` and calling `startActivityForResult()`. As [the documentation shows](https://github.com/commonsguy/cwac-cam2/blob/master/docs/CameraActivity.md#example-use-of-intentbuilder), it is two Java statements.

> Can you provide easy step to integrate camera capture module into fragment ?

No. That will be **orders of magnitude** more complex than is creating an `Intent` and calling `startActivityForResult()`.
