### ISSUE TITLE
LG K8 Preview stretched while recording video

### ISSUE THREAD

**Issue by mbernr** [commonsguy/cwac-cam2#323]
This is what it looks like on my LG K8 (Android 6.0):

Golfball before recording:
![capture _2017-05-15-16-39-54](https://cloud.githubusercontent.com/assets/18255672/26064012/fd1e6fd6-398f-11e7-8111-f85ed05e1362.png)

Golfball during recording: 
![capture _2017-05-15-16-40-07](https://cloud.githubusercontent.com/assets/18255672/26063977/e18dafb6-398f-11e7-884d-99e19bf162ee.png)

The actual output file looks fine.

**Comment by commonsguy** [comment]
That appears to be the same as issue #288, so I am going to close this as a duplicate. 

If you could confirm for me the specific model (the LG K8 seems to have several), I may pick one up to do some specific testing on it. Is yours the K350K, the K371, or perhaps something else?

**Comment by mbernr** [comment]
It is the LG-K350N

**Comment by commonsguy** [comment]
OK, thanks!
