### ISSUE TITLE
proguard NoSuchFieldError

### ISSUE THREAD

**Issue by itaybia** [commonsguy/cwac-cam2#333]
seems like adding only:
-keep class com.commonsware.cwac.** { *; }

to the proguard.pro is not enough. perhaps i misunderstood your meaning in the readme. but i had to add the eventbus proguard rules as well (from what you wrote, i got the feeling like the cwac keep should also keep all the eventbus classes).

also, the link you supplied for the rules is broken. it should be updated to:
https://github.com/krschultz/android-proguard-snippets/blob/c636c6c8448565e91e25a66f11fab3fca035c29c/libraries/proguard-eventbus-3.pro

**Comment by commonsguy** [comment]
I have made some adjustments to the README, including fixing the broken link. Thanks!
