### ISSUE TITLE
cwac-cam2 will be discontinued ?

### ISSUE THREAD

**Issue by leonardonogueira** [commonsguy/cwac-cam2#337]
Hello!

I've seen that the library cwac-cam2 will be discontinued in the coming weeks. You even recommend the use of other libraries, like CameraKit-Android.

This issue is just to make sure if this will really happen.

Is that correct?

**Comment by commonsguy** [comment]
In the future, please [follow the instructions for getting support](https://github.com/commonsguy/cwac-cam2#questions).

Yes, it will really happen.

The biggest difference between this library and alternatives like Fotoapparat and CameraKit-Android is that this library comes with "out of the box" activities, and those libraries do not. I am preparing a replacement for `cwac-cam2` that will provide an API akin to that of `cwac-cam2` and activities, but where the actual camera work is managed by your choice of Fotoapparat and CameraKit-Android. Once that replacement `cwac-cam2` library is released, I will discontinue work on this library.
