### ISSUE TITLE
NullPointerException before camera release

### ISSUE THREAD

**Issue by ppamorim** [commonsguy/cwac-cam2#39]
This happens only when I click at the "take picture" button until the camera isn't released.

    java.lang.NullPointerException
            at com.commonsware.cwac.cam2.ClassicCameraEngine$2.run(ClassicCameraEngine.java:134)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

**Comment by ppamorim** [comment]
add syncronize(object) and notify can solve this issue?

**Comment by commonsguy** [comment]
I doubt it. `session` was `null` when I called `takePicture()`, for some reason.

Could you please explain, in greater detail, how you are causing this crash? I do not know what "I click at the "take picture" button until the camera isn't released" means.

**Comment by commonsguy** [comment]
Well, I should be checking `session` for `null` before I call `takePicture()` on the `CameraEngine` anyway, so I have added that check. This does not address why `takePicture()` would have wound up being called in this state in the first place, though I am guessing that issue #44 is related.

**Comment by commonsguy** [comment]
Released in v0.1.1.
