### ISSUE TITLE
Changing CameraFragment Screws Up Preview Aspect Ratio

### ISSUE THREAD

**Issue by commonsguy** [commonsguy/cwac-cam2#42]
HTC M7 GPE, switching from RFC to FFC in portrait results in stretched preview.

Nexus 4, rotating from portrait to landscape while showing RFC results in stretched preview.

**Comment by commonsguy** [comment]
FYI, camera2 preview stretching comments from fadden: http://stackoverflow.com/questions/31614792/surfacetexture-preview-for-camera2-stretches-on-some-devices

**Comment by tplkn** [comment]
This commit add zoom for camera view in landscape mode (for the same distance for pen)
- before land: http://take.ms/Pey6c (correct)
- after port: http://take.ms/UjtD4 (correct) land: http://take.ms/9HNSb (wrong)

nexus 5, android 5.1

**Comment by commonsguy** [comment]
@tplkn AFAIK, that will be a natural side-effect of the full-screen preview. If you have suggestions on how to improve the algorithm, I am certainly up for any ideas. Note that I just committed another change, to take into account default-landscape devices, per issue #64. Thanks!

**Comment by commonsguy** [comment]
Released in v0.2.0
