### ISSUE TITLE
Disable FAB While Picture-Taking In Progress

### ISSUE THREAD

**Issue by commonsguy** [commonsguy/cwac-cam2#44]
Once the user taps the FAB, it (and the FAM) should be disabled, to prevent attempts to change things while the picture-taking is in progress. Only if we return to the fragment (e.g., user requests a re-take in the `ConfirmationFragment`) should we re-enable these.

**Comment by ppamorim** [comment]
What do you think to use syncronize(object) to fix this issue?

**Comment by commonsguy** [comment]
This is not a threading problem. Even to the extent that we try to treat it as a threading problem, one of the threads in question is the main application thread, and we do **not** want to be blocking the main application thread waiting for photo processing.

**Comment by ppamorim** [comment]
This is a little bit similar of #39, but I tested to sync that param and works fine at #39.

**Comment by commonsguy** [comment]
Released in v0.1.1.
