### ISSUE TITLE
Min sdk version

### ISSUE THREAD

**Issue by yazeed44** [commonsguy/cwac-cam2#47]
Is there a way to make it 14 ?

**Comment by commonsguy** [comment]
The current `minSdkVersion` is 15. There are [approximately zero devices in use today that are running Android 4.0](http://developer.android.com/about/dashboards/index.html) that have not been updated to at least 4.0.3 (where API Level 15 kicks in). As a result, I am not supporting anything lower than 15.

You are welcome to use the manifest merger process to override the `minSdkVersion` and set it to whatever you want, but I have no idea if it works and you are on your own for any problems that result.
