### ISSUE TITLE
Support FFC Mirror Option

### ISSUE THREAD

**Issue by commonsguy** [commonsguy/cwac-cam2#9]
Right now, pictures off the FFC are saved in their natural state, which will be mirrored with respect to what appears on the preview. Add a `mirrorFFC()`/`EXTRA_MIRROR_FFC` `boolean` option, defaulting to `false`, to mirror this. The best way to handle this would be to mirror the preview via `enterTheMatrix()` and leave the image alone.

**Comment by levibostian** [comment]
@commonsguy Is there anything I can do to get this done in the library? Are you looking to use the same logic as v1 of the library? I can check out the implementation there and try to replicate it in the new library.

**Comment by commonsguy** [comment]
@levibostian: I am imagining that this will take two forms:

1. `EXTRA_MIRROR_FFC_PREVIEW`, which leaves the image alone and mirrors the preview via the `Matrix` being set up in `adjustAspectRatio()`

2. `EXTRA_MIRROR_FFC_PICTURE`, which leaves the preview alone and mirrors the picture

The second approach is akin to what the original library is doing. The first approach is simpler to implement and should be more efficient (since I'm already doing a `Matrix` transformation anyway).

The first approach is mostly a matter of figuring out what sort of `postScale()` or whatever is necessary to add a horizontal mirror of the image, that doesn't interfere with the rest of the `Matrix` setup.

The second approach is a lot more involved, as I want to use the NDK for this sort of transform (as well as the EXIF-orientation-header fixup stuff). See issue #15.

I don't know which of these solutions addresses your concerns.

**Comment by levibostian** [comment]
Thank you, I appreciate it.

I was just asking to see if this was something I could help implement into the library so it was completed. I am in need of this feature so I was seeing if I could help put it in now. 

It seems a little more complex with my limited knowledge of the camera API and the full implementation of the library so I will wait. I am planning on implementing v1 of the library into my project and switch back once v2 is a little farther along.

**Comment by commonsguy** [comment]
`EXTRA_MIRROR_PREVIEW` is addressed in v0.3.0. `EXTRA_MIRROR_PICTURE` is covered by issue #100.
